### ISSUE TITLE
has_many models within the form

### ISSUE THREAD

**Issue by daverobertsfilm** [russellquinn/casein#88]
I am making a new app and I really love casein, saves a lot of time.
I am wondering however, if models that have has_many/belongs_to can sit within the form.

For example, I have made a tours model that has many subtours (similar to posts/comments relationship).
This all works fine in normal rails, but in casein I have two tabs, one saying tours, one subtours, but subtours obviously doesn't work because it can't read the tour id as it goes through.

is it possible to list the subtours in the relevant tour in casein (like I do in the app currently) and go to edit - and if so how?

Thanks in advance

**Comment by pedrorio** [comment]
I also have this question.

**Comment by admazzola** [comment]
You can go into the /views/casein/** folder and edit any of those files, it is pretty simple syntax and relatively easy to modify to your liking.  I do it all the time.  You could do a ruby loop in the html.erb file like this...

<% User.listing.all each do |u| %>
<div> <%= u.name %> </div>
<% end %>

**Comment by russellquinn** [comment]
Yeah, there's no specific generator to do this, but as @admazzola said it's relatively straight-forward to add. (The reason there's no generator is because there are so many ways a person might want to visualize one-to-many or many-to-many relationships and automating it is tough.)

However, Casein does have an option on the scaffold generator to just generate the table partials and not add to the other parts of the UI.  This means you can quickly render the child's partial in the parent's `show` view.

`--no-index = Excludes the index view and does not add the model to the navigation. The _table partial is still generated. This is useful when generating has/belongs relationships.`

FWIW, my typical steps for adding a basic one-to-many relationship is:

* Generate the scaffolding for the parent model
* Generate the partials for the child model using `--no-index`
* Add a list of the children to the parent's `show.html.erb` view, by putting something like this at the bottom of the page (e.g. `User` has many `Purchases`):

`<% if @user.purchases.count %>
	
	<h2>Purchases</h2>

	<%= render :partial => 'casein/purchases/table', :locals => { :purchases => @user.purchases } %>

<% end %>`

* Then if you want to add the ability to create a new child, you can add this into the parent's sidebar. So, again, in the parent model's `show.html.erb` view you can find the `content_for :sidebar` block and add a button:

`<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_users_path %></li>
	<li><%= link_to "#{casein_show_icon "plus-sign"}Add purchase".html_safe, new_casein_purchase_path(:user_id => @user.id) %></li>
<% end %>`

I hope that helps!
